name: Actualización SWN
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Instalar herramientas
        run: |
          pip install feedparser googletrans==4.0.0-rc1 spacy requests
          python -m spacy download es_core_news_lg
      - name: Ejecutar Cerebro
        run: python generador_noticias.py
      - name: Subir cambios
        run: |
          git config --global user.name "Cerebro SWN"
          git config --global user.email "swn@github.com"
          git add noticias.json
          git commit -m "Sincronización histórica 1970-2026" || echo "Sin cambios"
          git push
