name: Actualización Eureka
on:
  schedule:
    - cron: '0 */6 * * *' # Se ejecutará cada 6 horas para mantenerlo fresco
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurando Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalando Librerías
        run: |
          pip install feedparser googletrans==4.0.0-rc1 spacy requests
          python -m spacy download es_core_news_lg

      - name: Generando Noticias Nuevas
        run: python generador_noticias.py

      - name: Forzando actualización en Repositorio
        run: |
          git config --global user.name "Cerebro-Eureka"
          git config --global user.email "eureka@github.com"
          git add noticias.json
          git commit -m "Actualización Eureka: $(date)" || echo "Sin cambios"
          git push origin main
